"""empty message

Revision ID: 782cf0b2c534
Revises: 824fa6ea87f6
Create Date: 2026-01-19 20:27:50.532966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782cf0b2c534'
down_revision = '824fa6ea87f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    # ### end Alembic commands ###
